### ISSUE TITLE
Add polarity to the download

### ISSUE THREAD

**Issue by julianflowers** [PublicHealthEngland/fingertipsR#15]
Can we add polarity to the download

**Comment by sebastian-fox** [comment]
@danielflint I don't think I can see this in the indicator metadata csv. Where is polairites available on the API?

**Comment by danielflint** [comment]
The polarity can vary for an indicator between profiles so in PHOLIO it is associated with the profile groupings instead of the indicator metadata. The polarity ID is in this call but it would be easier for you if we added an option to include the possible polarities:

https://testprofiles.phe.org.uk/api/latest_data/all_indicators_in_profile_group_for_child_areas?group_id=3007000&area_type_id=101&parent_area_code=E12000004&profile_id=26

**Comment by sebastian-fox** [comment]
Thanks - I see. I can see the polarity ID in that call. I currently don't touch the latest_data part of the api with any of my functions.
Would it be difficult for you to add possible polarities?

**Comment by danielflint** [comment]
I've added it but I'm going to wait until after the deployment on Jul 4 to release it to the test site. The polarities can vary and aren't always visible on the site so they'll need checking by the analysts.

**Comment by sebastian-fox** [comment]
Thanks Daniel. This is great. I'll have a look at it. Seb

**Comment by sebastian-fox** [comment]
This is now available in `indicator_metadata` function as a result of the Fingertips update today. Thanks again Daniel (+ team)
